CREATE TABLE `game_players` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`username` varchar(64) NOT NULL,
	`realName` varchar(128) NOT NULL,
	`passwordHash` varchar(256) NOT NULL,
	`avatarKey` varchar(32) NOT NULL DEFAULT 'DUOLINCITO',
	`language` varchar(5) NOT NULL DEFAULT 'es',
	`linceCoins` int NOT NULL DEFAULT 0,
	`xp` int NOT NULL DEFAULT 0,
	`currentLevel` int NOT NULL DEFAULT 1,
	`totalPromptsWritten` int NOT NULL DEFAULT 0,
	`streak` int NOT NULL DEFAULT 0,
	`lastPlayedDate` varchar(10) NOT NULL DEFAULT '',
	`levelsData` json,
	`dailyRewardsData` json,
	`emailVerified` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastLoginAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `game_players_id` PRIMARY KEY(`id`),
	CONSTRAINT `game_players_email_unique` UNIQUE(`email`),
	CONSTRAINT `game_players_username_unique` UNIQUE(`username`)
);
