import { describe, it, expect } from "vitest";

// Test the disclaimer texts structure (since we can't render React in server tests)
describe("FictionalDisclaimer texts", () => {
  const TEXTS = {
    es: {
      banner: "Todos los avatares de esta sección son personajes ficticios creados con IA con fines educativos. No representan ni están afiliados a ninguna persona real.",
      badge: "Personaje ficticio",
      badgeInspired: "Personaje ficticio",
      inline: "Este es un personaje ficticio creado con IA con fines educativos. No representa ni está afiliado a ninguna persona real.",
      chat: "Estás hablando con un personaje ficticio creado con IA. Las respuestas son generadas por inteligencia artificial y no representan las opiniones de ninguna persona real.",
    },
    en: {
      banner: "All avatars in this section are fictional characters created with AI. Any resemblance to real people is part of an artistic and educational tribute. They do not represent nor are affiliated with the mentioned individuals.",
      badge: "Fictional character",
      badgeInspired: "Fictional character inspired by",
      inline: "This is a fictional AI-generated character for educational purposes. It does not represent nor is affiliated with any real person.",
      chat: "You are chatting with a fictional AI-generated character. Responses are generated by artificial intelligence and do not represent the opinions of any real person.",
    },
    zh: {
      banner: "本部分所有头像均为AI创建的虚构角色。与真实人物的任何相似之处均为艺术和教育致敬的一部分。它们不代表也不隶属于所提及的个人。",
      badge: "虚构角色",
      badgeInspired: "灵感来自",
      inline: "这是一个为教育目的而创建的AI虚构角色。它不代表也不隶属于任何真实人物。",
      chat: "您正在与AI创建的虚构角色对话。回复由人工智能生成，不代表任何真实人物的观点。",
    },
  };

  it("should have all 3 languages", () => {
    expect(Object.keys(TEXTS)).toEqual(["es", "en", "zh"]);
  });

  it("should have all required keys per language", () => {
    const requiredKeys = ["banner", "badge", "badgeInspired", "inline", "chat"];
    for (const lang of Object.keys(TEXTS) as Array<keyof typeof TEXTS>) {
      for (const key of requiredKeys) {
        expect(TEXTS[lang]).toHaveProperty(key);
        expect(typeof TEXTS[lang][key as keyof typeof TEXTS[typeof lang]]).toBe("string");
        expect((TEXTS[lang][key as keyof typeof TEXTS[typeof lang]] as string).length).toBeGreaterThan(1);
      }
    }
  });

  it("banner text should mention fictional and AI", () => {
    expect(TEXTS.es.banner).toContain("ficticios");
    expect(TEXTS.es.banner).toContain("IA");
    expect(TEXTS.en.banner).toContain("fictional");
    expect(TEXTS.en.banner).toContain("AI");
  });

  it("chat text should warn about AI-generated responses", () => {
    expect(TEXTS.es.chat).toContain("inteligencia artificial");
    expect(TEXTS.en.chat).toContain("artificial intelligence");
    expect(TEXTS.zh.chat).toContain("人工智能");
  });

  it("badge text should be short and clear", () => {
    expect(TEXTS.es.badge.length).toBeLessThan(30);
    expect(TEXTS.en.badge.length).toBeLessThan(30);
    expect(TEXTS.zh.badge.length).toBeLessThan(10);
  });

  it("badgeInspired should work with real name", () => {
    const realName = "VOLTZLIN";
    const result = `${TEXTS.es.badgeInspired} ${realName}`;
    expect(result).toBe("Personaje ficticio VOLTZLIN");
  });

  it("inline text should mention educational purposes", () => {
    expect(TEXTS.es.inline).toContain("educativos");
    expect(TEXTS.en.inline).toContain("educational");
  });

  // Test that groups needing disclaimers are correctly identified
  const GROUPS_NEEDING_DISCLAIMER = ["urbano", "zaragoza"];
  const GROUPS_NO_DISCLAIMER = ["familia", "especialistas", "aragoneses"];

  it("should identify which groups need disclaimers", () => {
    expect(GROUPS_NEEDING_DISCLAIMER).toContain("urbano");
    expect(GROUPS_NEEDING_DISCLAIMER).toContain("zaragoza");
    expect(GROUPS_NO_DISCLAIMER).not.toContain("urbano");
    expect(GROUPS_NO_DISCLAIMER).not.toContain("zaragoza");
  });

  it("fictional characters (familia, especialistas, aragoneses) should NOT need disclaimers", () => {
    for (const group of GROUPS_NO_DISCLAIMER) {
      expect(GROUPS_NEEDING_DISCLAIMER).not.toContain(group);
    }
  });
});
