import { createContext, useContext, useState, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Header
    "nav.thesis": "Tesis",
    "nav.product": "Producto",
    "nav.roadmap": "Roadmap",
    "nav.roles": "Roles",
    "nav.projections": "Proyecciones",
    "nav.partnership": "Partnership",
    "nav.downloads": "Descargas",
    "nav.contact": "Contacto",
    "nav.contactBtn": "Contactar",

    // Hero
    "hero.subtitle": "Propuesta de Partnership Estratégico",
    "hero.tagline": '"Aprende IA. Sé más lince."',
    "hero.description": "Aprende IA Jugando",
    "hero.ctaPrimary": "Ver Tesis de Inversión",
    "hero.ctaSecondary": "Contactar Ahora",

    // Metrics Bar
    "metrics.market": "Mercado Apps Educativas 2025",
    "metrics.talentGap": "Brecha de Talento IA",
    "metrics.competition": "Competencia Directa",
    "metrics.roi": "ROI Potencial Partner",

    // Thesis Section
    "thesis.section": "Sección 1",
    "thesis.title": "Tesis de",
    "thesis.titleHighlight": "Inversión",
    "thesis.quote": '"La formación en herramientas de IA generativa seguirá el mismo patrón que la formación en idiomas: quien aplique gamificación extrema y experiencia de usuario superior capturará el mercado masivo."',
    
    // Why invest now
    "thesis.firstMover": "Primera Ventaja",
    "thesis.firstMoverDesc": "No existe competencia directa que combine aprendizaje jugando + herramientas IA + VR/AR + tutor IA",
    "thesis.designed": "100% Diseñado",
    "thesis.designedDesc": "3 años de trabajo invertidos, listo para desarrollo inmediato",
    "thesis.market": "Mercado en Explosión",
    "thesis.marketDesc": "La IA generativa está en su pico de adopción (2024-2027)",
    "thesis.provenModel": "Modelo Probado",
    "thesis.provenModelDesc": "Duolingo validó que aprender jugando funciona (500M+ usuarios)",
    "thesis.returns": "Retorno Atractivo",
    "thesis.returnsDesc": "7x-15x en 5 años con riesgo controlado",

    // Duolingo precedent
    "thesis.duolingoTitle": "El Precedente Duolingo",
    "thesis.mau": "Usuarios Activos Mensuales",
    "thesis.paidUsers": "Usuarios de Pago (7.7%)",
    "thesis.arr": "ARR Anual",
    "thesis.valuation": "Valoración (15x ARR)",
    "thesis.source": "Fuente: Duolingo Q4 2024 Earnings Report",

    // Deal metrics
    "thesis.dealMetrics": "Métricas Clave del Deal",
    "thesis.upfrontPayment": "Pago Inicial (Licencia IP)",
    "thesis.revenueSharePartner": "Revenue Share Partner",
    "thesis.revenueShareFounder": "Revenue Share Fundador",
    "thesis.projectedARR": "ARR Proyectado Año 5",
    "thesis.estimatedReturn": "Retorno Estimado Partner (5 años)",
    "thesis.roiMultiple": "Múltiplo ROI",
    "thesis.negotiable": "(negociable)",

    // Product Section
    "product.section": "Sección 2",
    "product.title": "El",
    "product.titleHighlight": "Producto",
    "product.subtitle": "Una app completa para aprender jugando",
    "product.levels": "Niveles",
    "product.levelsDesc": "Progresión desde básico hasta experto en IA generativa",
    "product.worlds": "Mundos",
    "product.worldsDesc": "Universos temáticos que cubren todos los dominios de IA",
    "product.courses": "Cursos",
    "product.coursesDesc": "Contenido especializado para diferentes industrias",
    "product.virtualTwins": "Gemelos Virtuales",
    "product.virtualTwinsDesc": "Personajes IA que te enseñan a tu ritmo y nivel",
    "product.gamification": "Aprender Jugando",
    "product.gamificationDesc": "Gana puntos, medallas, sube en el ranking y supera retos diarios",
    "product.availability": "Disponibilidad",
    "product.availabilityDesc": "Aprende cuando quieras, donde quieras, a tu ritmo",
    "product.vegaSystem": "Sistema V·E·G·A — Tu aprendizaje se adapta a ti",
    "product.validation": "Validación",
    "product.evaluation": "Evaluación",
    "product.generation": "Generación",
    "product.adaptation": "Adaptación",

    // Roadmap Section
    "roadmap.section": "Sección 3",
    "roadmap.title": "Roadmap de",
    "roadmap.titleHighlight": "Desarrollo",
    "roadmap.subtitle": "Tiempos a definir por el socio desarrollador",
    "roadmap.phase1": "Fase 1",
    "roadmap.phase1Title": "Fundación",
    "roadmap.phase1Duration": "6-9 meses",
    "roadmap.phase1Item1": "Arquitectura core de la plataforma",
    "roadmap.phase1Item2": "Primeros 3 mundos (30 niveles)",
    "roadmap.phase1Item3": "Sistema básico de juego y recompensas",
    "roadmap.phase1Item4": "Autenticación y perfiles de usuario",
    "roadmap.phase1Item5": "MVP iOS y Android",
    "roadmap.phase1Milestone": "Lanzamiento MVP",
    "roadmap.phase2": "Fase 2",
    "roadmap.phase2Title": "Crecimiento",
    "roadmap.phase2Duration": "6-12 meses",
    "roadmap.phase2Item1": "Sistema adaptativo V·E·G·A",
    "roadmap.phase2Item2": "Integración de Gemelos Virtuales",
    "roadmap.phase2Item3": "Expansión a 7 mundos (70 niveles)",
    "roadmap.phase2Item4": "Funcionalidades B2B enterprise",
    "roadmap.phase2Item5": "Marketing y adquisición de usuarios",
    "roadmap.phase2Milestone": "100K Usuarios",
    "roadmap.phase3": "Fase 3",
    "roadmap.phase3Title": "Escalado",
    "roadmap.phase3Duration": "12-18 meses",
    "roadmap.phase3Item1": "Completar 10 mundos (100 niveles)",
    "roadmap.phase3Item2": "Marketplace de contenido terceros",
    "roadmap.phase3Item3": "Analytics y reporting avanzado",
    "roadmap.phase3Item4": "Expansión internacional",
    "roadmap.phase3Item5": "Programas de certificación",
    "roadmap.phase3Milestone": "1M Usuarios",
    "roadmap.milestone": "Hito",
    "roadmap.flexibility": "Flexibilidad:",
    "roadmap.flexibilityText": "Los tiempos exactos dependen de los recursos y prioridades del partner. El enfoque por fases permite aprendizaje iterativo y feedback del mercado.",

    // Roles Section
    "roles.section": "Sección 4",
    "roles.title": "Roles y",
    "roles.titleHighlight": "Responsabilidades",
    "roles.subtitle": "División clara de funciones entre fundador y socio desarrollador",
    "roles.founderTab": "Fundador",
    "roles.partnerTab": "Socio Desarrollador",
    "roles.founderTitle": "LINCE — CEO & Especialista IA",
    "roles.founderSubtitle": "Responsable del contenido, estrategia y visión del producto",
    "roles.founderItem1": "Creación de contenido IA y diseño curricular",
    "roles.founderItem2": "Dirección creativa y estrategia de marca",
    "roles.founderItem3": "Metodología educativa y sistema V·E·G·A",
    "roles.founderItem4": "Control de calidad y validación de contenido",
    "roles.founderItem5": "Construcción de comunidad y thought leadership",
    "roles.founderItem6": "Relaciones con expertos y partners de contenido",
    "roles.partnerTitle": "Socio Desarrollador",
    "roles.partnerSubtitle": "Responsable de la ejecución técnica y operaciones",
    "roles.partnerItem1": "Desarrollo técnico completo (app + backend)",
    "roles.partnerItem2": "Infraestructura y operaciones cloud",
    "roles.partnerItem3": "Marketing, adquisición de usuarios y growth",
    "roles.partnerItem4": "Soporte al cliente y operaciones",
    "roles.partnerItem5": "Legal, finanzas y compliance",
    "roles.partnerItem6": "Gestión de equipo técnico y recursos",
    "roles.synergy": "Sinergia:",
    "roles.synergyText": "Esta división permite que cada parte se enfoque en sus fortalezas. El fundador aporta el conocimiento de dominio y visión; el partner aporta capacidad de ejecución y escala.",

    // Projections Section
    "projections.section": "Sección 5",
    "projections.title": "Proyecciones",
    "projections.titleHighlight": "Financieras",
    "projections.subtitle": "Escenario base conservador a 5 años",
    "projections.metric": "Métrica",
    "projections.year1": "Año 1",
    "projections.year2": "Año 2",
    "projections.year3": "Año 3",
    "projections.year4": "Año 4",
    "projections.year5": "Año 5",
    "projections.downloads": "Descargas",
    "projections.mau": "MAU",
    "projections.payingUsers": "Usuarios de Pago",
    "projections.arpu": "ARPU",
    "projections.arr": "ARR",
    "projections.cumulativeRevenue": "Ingresos Acumulados 5 Años",
    "projections.conversionRate": "Tasa de Conversión Objetivo",
    "projections.year5ARR": "ARR Año 5",
    "projections.calculation": "Cálculo:",
    "projections.calculationText": "ARR = Usuarios de Pago × ARPU × 12. Estimaciones conservadoras basadas en benchmarks de Duolingo (8% conversión) con 25% de incremento por pricing premium B2B.",

    // ARR Explanation
    "arr.title": "Entendiendo",
    "arr.titleHighlight": "ARR y ARPU",
    "arr.whatIsARR": "¿Qué es ARR?",
    "arr.arrDefinition": "Annual Recurring Revenue (Ingresos Recurrentes Anuales). Es el ingreso anualizado de las suscripciones activas.",
    "arr.whatIsARPU": "¿Qué es ARPU?",
    "arr.arpuDefinition": "Average Revenue Per User (Ingreso Promedio por Usuario). Es cuánto paga en promedio cada usuario de pago al mes.",
    "arr.formula": "Fórmula",
    "arr.formulaText": "ARR = Usuarios de Pago × ARPU × 12 meses",
    "arr.example": "Ejemplo Año 5",
    "arr.exampleText": "60,000 usuarios × €15/mes × 12 = €10.8M ARR",

    // Partnership Section
    "partnership.section": "Sección 6",
    "partnership.title": "Estructura del",
    "partnership.titleHighlight": "Partnership",
    "partnership.upfrontLabel": "Pago Inicial",
    "partnership.upfrontValue": "€150K-200K",
    "partnership.upfrontDesc": "Licencia de IP por 3 años de desarrollo y diseño",
    "partnership.developmentLabel": "Inversión en Desarrollo",
    "partnership.developmentValue": "€285K-545K",
    "partnership.developmentDesc": "Partner cubre desarrollo, infraestructura y marketing",
    "partnership.revenueLabel": "Revenue Share",
    "partnership.revenueValue": "65-70% / 30-35%",
    "partnership.revenueDesc": "Fundador / Partner (negociable hasta 50%)",
    "partnership.founderResponsibilities": "Responsabilidades del Fundador",
    "partnership.partnerResponsibilities": "Responsabilidades del Partner",
    "partnership.keyAdvantage": "Ventaja clave:",
    "partnership.keyAdvantageText": "El fundador retiene 100% del equity. El partner recibe revenue share sin dilución de equity. Ambas partes alineadas para el éxito a largo plazo.",

    // ROI Section
    "roi.section": "Sección 7",
    "roi.title": "Análisis de",
    "roi.titleHighlight": "ROI del Partner",
    "roi.upfrontPayment": "Pago Inicial",
    "roi.developmentCosts": "Costes de Desarrollo",
    "roi.totalInvestment": "Inversión Total",
    "roi.scenariosTitle": "Escenarios de Retorno a 5 Años (35% Partner Share)",
    "roi.conservative": "Conservador",
    "roi.baseCase": "Caso Base",
    "roi.optimistic": "Optimista",
    "roi.fiveYearRevenue": "Ingresos 5 Años",
    "roi.partnerShare": "Parte del Partner",
    "roi.netReturn": "Retorno Neto",
    "roi.roiMultiple": "Múltiplo ROI",
    "roi.benchmark": "Benchmark:",
    "roi.benchmarkText": "Las inversiones típicas en apps educativas retornan 3-5x. El posicionamiento único de LINCE y la ventaja de ser los primeros justifican expectativas de retorno más altas.",

    // Risks Section
    "risks.section": "Sección 8",
    "risks.title": "Análisis de",
    "risks.titleHighlight": "Riesgos",
    "risks.risk": "Riesgo",
    "risks.mitigation": "Mitigación",
    "risks.marketAdoption": "Adopción de Mercado",
    "risks.marketAdoptionDesc": "Los usuarios pueden preferir métodos tradicionales o plataformas existentes",
    "risks.marketAdoptionMitigation": "Modelo gratuito reduce barrera. Aprender jugando funciona (Duolingo: 500M+ usuarios)",
    "risks.execution": "Complejidad de Ejecución",
    "risks.executionDesc": "El desarrollo técnico puede sufrir retrasos o sobrecostes",
    "risks.executionMitigation": "Enfoque de desarrollo por fases. MVP en 6-9 meses. Partner asume riesgo técnico",
    "risks.competition": "Entrada de Competencia",
    "risks.competitionDesc": "Duolingo u otros pueden entrar en el espacio de educación IA",
    "risks.competitionMitigation": "Ventaja de ser los primeros. 3 años de desarrollo de contenido. Conocimiento profundo en IA",
    "risks.technology": "Evolución Tecnológica",
    "risks.technologyDesc": "Cambios rápidos en IA pueden requerir actualizaciones constantes de contenido",
    "risks.technologyMitigation": "Fundador es especialista en IA. Sistema V·E·G·A permite contenido adaptativo. Modelo de actualización continua",
    "risks.assessment": "Evaluación de riesgo:",
    "risks.assessmentText": "Todos los riesgos identificados tienen mitigaciones viables. La estructura del partnership distribuye el riesgo apropiadamente entre fundador (contenido) y partner (ejecución).",
    "risks.globalRisk": "RIESGO GLOBAL: MODERADO",

    // Downloads Section
    "downloads.section": "Recursos",
    "downloads.title": "Documentos",
    "downloads.titleHighlight": "Descargables",
    "downloads.subtitle": "Descarga la presentación ejecutiva en español o inglés",
    "downloads.spanishTitle": "Presentación Ejecutiva",
    "downloads.spanishSubtitle": "Versión en Español",
    "downloads.spanishDesc": "Propuesta completa de partnership con análisis de mercado, proyecciones financieras, estructura del acuerdo y roadmap de desarrollo.",
    "downloads.spanishPages": "PDF · 13 páginas",
    "downloads.spanishBtn": "Descargar PDF",
    "downloads.englishTitle": "Executive Presentation",
    "downloads.englishSubtitle": "English Version",
    "downloads.englishDesc": "Complete partnership proposal with market analysis, financial projections, deal structure and development roadmap.",
    "downloads.englishPages": "PDF · 13 pages",
    "downloads.englishBtn": "Download PDF",
    "downloads.confidential": "Documentos confidenciales. Por favor, no distribuir sin autorización.",

    // Contact Section
    "contact.cta": "Llamado a la Acción",
    "contact.title": '"El Balón Está en',
    "contact.titleHighlight": "Su Tejado",
    "contact.exclusiveUntil": "Propuesta Exclusiva Válida Hasta",
    "contact.deadline": "10 de Febrero de 2026",
    "contact.nextSteps": "Próximos Pasos",
    "contact.step1": "Reunión",
    "contact.step2": "NDA",
    "contact.step3": "Due Diligence",
    "contact.step4": "Firma",
    "contact.ready": "¿Listo para dar el siguiente paso?",
    "contact.contactNow": "Contactar Ahora",

    // Footer
    "footer.rights": "© 2026 LINCE. Todos los derechos reservados.",
    "footer.ballInCourt": '"El balón está en su tejado"',
    "footer.confidential": "DOCUMENTO 100% CONFIDENCIAL",
  },
  en: {
    // Header
    "nav.thesis": "Thesis",
    "nav.product": "Product",
    "nav.roadmap": "Roadmap",
    "nav.roles": "Roles",
    "nav.projections": "Projections",
    "nav.partnership": "Partnership",
    "nav.downloads": "Downloads",
    "nav.contact": "Contact",
    "nav.contactBtn": "Contact",

    // Hero
    "hero.subtitle": "Strategic Partnership Proposal",
    "hero.tagline": '"Learn AI. Be smarter."',
    "hero.description": "Learn AI by Playing",
    "hero.ctaPrimary": "View Investment Thesis",
    "hero.ctaSecondary": "Contact Now",

    // Metrics Bar
    "metrics.market": "Educational Apps Market 2025",
    "metrics.talentGap": "AI Talent Gap",
    "metrics.competition": "Direct Competition",
    "metrics.roi": "Partner Potential ROI",

    // Thesis Section
    "thesis.section": "Section 1",
    "thesis.title": "Investment",
    "thesis.titleHighlight": "Thesis",
    "thesis.quote": '"Training in generative AI tools will follow the same pattern as language training: whoever applies extreme gamification and superior user experience will capture the mass market."',
    
    // Why invest now
    "thesis.firstMover": "First Mover",
    "thesis.firstMoverDesc": "No direct competition combining learn-by-playing + AI tools + VR/AR + AI tutor",
    "thesis.designed": "100% Designed",
    "thesis.designedDesc": "3 years of work invested, ready for immediate development",
    "thesis.market": "Exploding Market",
    "thesis.marketDesc": "Generative AI is at its peak adoption (2024-2027)",
    "thesis.provenModel": "Proven Model",
    "thesis.provenModelDesc": "Duolingo validated that learning by playing works (500M+ users)",
    "thesis.returns": "Attractive Returns",
    "thesis.returnsDesc": "7x-15x in 5 years with controlled risk",

    // Duolingo precedent
    "thesis.duolingoTitle": "The Duolingo Precedent",
    "thesis.mau": "Monthly Active Users",
    "thesis.paidUsers": "Paid Users (7.7%)",
    "thesis.arr": "Annual ARR",
    "thesis.valuation": "Valuation (15x ARR)",
    "thesis.source": "Source: Duolingo Q4 2024 Earnings Report",

    // Deal metrics
    "thesis.dealMetrics": "Key Deal Metrics",
    "thesis.upfrontPayment": "Upfront Payment (IP License)",
    "thesis.revenueSharePartner": "Partner Revenue Share",
    "thesis.revenueShareFounder": "Founder Revenue Share",
    "thesis.projectedARR": "Projected Year 5 ARR",
    "thesis.estimatedReturn": "Estimated Partner Return (5 years)",
    "thesis.roiMultiple": "ROI Multiple",
    "thesis.negotiable": "(negotiable)",

    // Product Section
    "product.section": "Section 2",
    "product.title": "The",
    "product.titleHighlight": "Product",
    "product.subtitle": "A complete app to learn by playing",
    "product.levels": "Levels",
    "product.levelsDesc": "Progression from basic to expert in generative AI",
    "product.worlds": "Worlds",
    "product.worldsDesc": "Thematic universes covering all AI domains",
    "product.courses": "Courses",
    "product.coursesDesc": "Specialized content for different industries",
    "product.virtualTwins": "Virtual Twins",
    "product.virtualTwinsDesc": "AI characters that teach you at your pace and level",
    "product.gamification": "Learn by Playing",
    "product.gamificationDesc": "Earn points, badges, climb rankings, beat daily challenges",
    "product.availability": "Availability",
    "product.availabilityDesc": "Learn whenever, wherever, at your own pace",
    "product.vegaSystem": "V·E·G·A System — Your learning adapts to you",
    "product.validation": "Validation",
    "product.evaluation": "Evaluation",
    "product.generation": "Generation",
    "product.adaptation": "Adaptation",

    // Roadmap Section
    "roadmap.section": "Section 3",
    "roadmap.title": "Development",
    "roadmap.titleHighlight": "Roadmap",
    "roadmap.subtitle": "Timeline to be defined by development partner",
    "roadmap.phase1": "Phase 1",
    "roadmap.phase1Title": "Foundation",
    "roadmap.phase1Duration": "6-9 months",
    "roadmap.phase1Item1": "Core platform architecture",
    "roadmap.phase1Item2": "First 3 worlds (30 levels)",
    "roadmap.phase1Item3": "Basic game and rewards system",
    "roadmap.phase1Item4": "User authentication and profiles",
    "roadmap.phase1Item5": "iOS and Android MVP",
    "roadmap.phase1Milestone": "MVP Launch",
    "roadmap.phase2": "Phase 2",
    "roadmap.phase2Title": "Growth",
    "roadmap.phase2Duration": "6-12 months",
    "roadmap.phase2Item1": "V·E·G·A adaptive system",
    "roadmap.phase2Item2": "Virtual Twins integration",
    "roadmap.phase2Item3": "Expand to 7 worlds (70 levels)",
    "roadmap.phase2Item4": "B2B enterprise features",
    "roadmap.phase2Item5": "Marketing and user acquisition",
    "roadmap.phase2Milestone": "100K Users",
    "roadmap.phase3": "Phase 3",
    "roadmap.phase3Title": "Scale",
    "roadmap.phase3Duration": "12-18 months",
    "roadmap.phase3Item1": "Complete 10 worlds (100 levels)",
    "roadmap.phase3Item2": "Third-party content marketplace",
    "roadmap.phase3Item3": "Advanced analytics and reporting",
    "roadmap.phase3Item4": "International expansion",
    "roadmap.phase3Item5": "Certification programs",
    "roadmap.phase3Milestone": "1M Users",
    "roadmap.milestone": "Milestone",
    "roadmap.flexibility": "Flexibility:",
    "roadmap.flexibilityText": "Exact timelines depend on partner resources and priorities. Phased approach allows iterative learning and market feedback.",

    // Roles Section
    "roles.section": "Section 4",
    "roles.title": "Roles &",
    "roles.titleHighlight": "Responsibilities",
    "roles.subtitle": "Clear division of functions between founder and development partner",
    "roles.founderTab": "Founder",
    "roles.partnerTab": "Development Partner",
    "roles.founderTitle": "LINCE — CEO & AI Specialist",
    "roles.founderSubtitle": "Responsible for content, strategy and product vision",
    "roles.founderItem1": "AI content creation and curriculum design",
    "roles.founderItem2": "Creative direction and brand strategy",
    "roles.founderItem3": "Educational methodology and V·E·G·A system",
    "roles.founderItem4": "Quality control and content validation",
    "roles.founderItem5": "Community building and thought leadership",
    "roles.founderItem6": "Relationships with experts and content partners",
    "roles.partnerTitle": "Development Partner",
    "roles.partnerSubtitle": "Responsible for technical execution and operations",
    "roles.partnerItem1": "Full technical development (app + backend)",
    "roles.partnerItem2": "Infrastructure and cloud operations",
    "roles.partnerItem3": "Marketing, user acquisition and growth",
    "roles.partnerItem4": "Customer support and operations",
    "roles.partnerItem5": "Legal, finance and compliance",
    "roles.partnerItem6": "Technical team and resource management",
    "roles.synergy": "Synergy:",
    "roles.synergyText": "This division allows each party to focus on their strengths. The founder brings domain knowledge and vision; the partner brings execution capability and scale.",

    // Projections Section
    "projections.section": "Section 5",
    "projections.title": "Financial",
    "projections.titleHighlight": "Projections",
    "projections.subtitle": "Conservative base scenario over 5 years",
    "projections.metric": "Metric",
    "projections.year1": "Year 1",
    "projections.year2": "Year 2",
    "projections.year3": "Year 3",
    "projections.year4": "Year 4",
    "projections.year5": "Year 5",
    "projections.downloads": "Downloads",
    "projections.mau": "MAU",
    "projections.payingUsers": "Paying Users",
    "projections.arpu": "ARPU",
    "projections.arr": "ARR",
    "projections.cumulativeRevenue": "5-Year Cumulative Revenue",
    "projections.conversionRate": "Target Conversion Rate",
    "projections.year5ARR": "Year 5 ARR",
    "projections.calculation": "Calculation:",
    "projections.calculationText": "ARR = Paying Users × ARPU × 12. Conservative estimates based on Duolingo benchmarks (8% conversion) with 25% uplift for B2B premium pricing.",

    // ARR Explanation
    "arr.title": "Understanding",
    "arr.titleHighlight": "ARR & ARPU",
    "arr.whatIsARR": "What is ARR?",
    "arr.arrDefinition": "Annual Recurring Revenue. The annualized revenue from active subscriptions.",
    "arr.whatIsARPU": "What is ARPU?",
    "arr.arpuDefinition": "Average Revenue Per User. How much each paying user pays on average per month.",
    "arr.formula": "Formula",
    "arr.formulaText": "ARR = Paying Users × ARPU × 12 months",
    "arr.example": "Year 5 Example",
    "arr.exampleText": "60,000 users × €15/month × 12 = €10.8M ARR",

    // Partnership Section
    "partnership.section": "Section 6",
    "partnership.title": "Partnership",
    "partnership.titleHighlight": "Structure",
    "partnership.upfrontLabel": "Upfront Payment",
    "partnership.upfrontValue": "€150K-200K",
    "partnership.upfrontDesc": "IP license for 3 years of development and design",
    "partnership.developmentLabel": "Development Investment",
    "partnership.developmentValue": "€285K-545K",
    "partnership.developmentDesc": "Partner covers development, infrastructure and marketing",
    "partnership.revenueLabel": "Revenue Share",
    "partnership.revenueValue": "65-70% / 30-35%",
    "partnership.revenueDesc": "Founder / Partner (negotiable up to 50%)",
    "partnership.founderResponsibilities": "Founder Responsibilities",
    "partnership.partnerResponsibilities": "Partner Responsibilities",
    "partnership.keyAdvantage": "Key advantage:",
    "partnership.keyAdvantageText": "Founder retains 100% equity. Partner receives revenue share without equity dilution. Both parties aligned for long-term success.",

    // ROI Section
    "roi.section": "Section 7",
    "roi.title": "Partner",
    "roi.titleHighlight": "ROI Analysis",
    "roi.upfrontPayment": "Upfront Payment",
    "roi.developmentCosts": "Development Costs",
    "roi.totalInvestment": "Total Investment",
    "roi.scenariosTitle": "5-Year Return Scenarios (35% Partner Share)",
    "roi.conservative": "Conservative",
    "roi.baseCase": "Base Case",
    "roi.optimistic": "Optimistic",
    "roi.fiveYearRevenue": "5-Year Revenue",
    "roi.partnerShare": "Partner Share",
    "roi.netReturn": "Net Return",
    "roi.roiMultiple": "ROI Multiple",
    "roi.benchmark": "Benchmark:",
    "roi.benchmarkText": "Typical educational app investments return 3-5x. LINCE's unique positioning and first-mover advantage justify higher return expectations.",

    // Risks Section
    "risks.section": "Section 8",
    "risks.title": "Risk",
    "risks.titleHighlight": "Analysis",
    "risks.risk": "Risk",
    "risks.mitigation": "Mitigation",
    "risks.marketAdoption": "Market Adoption",
    "risks.marketAdoptionDesc": "Users may prefer traditional methods or existing platforms",
    "risks.marketAdoptionMitigation": "Free model reduces barrier. Learning by playing proven for engagement (Duolingo: 500M+ users)",
    "risks.execution": "Execution Complexity",
    "risks.executionDesc": "Technical development may face delays or cost overruns",
    "risks.executionMitigation": "Phased development approach. MVP in 6-9 months. Partner assumes technical risk",
    "risks.competition": "Competition Entry",
    "risks.competitionDesc": "Duolingo or others may enter AI education space",
    "risks.competitionMitigation": "First-mover advantage. 3 years of content development. Deep AI expertise",
    "risks.technology": "Technology Evolution",
    "risks.technologyDesc": "Rapid AI changes may require constant content updates",
    "risks.technologyMitigation": "Founder is AI specialist. V·E·G·A system enables adaptive content. Continuous update model",
    "risks.assessment": "Risk assessment:",
    "risks.assessmentText": "All identified risks have viable mitigations. Partnership structure distributes risk appropriately between founder (content) and partner (execution).",
    "risks.globalRisk": "GLOBAL RISK: MODERATE",

    // Downloads Section
    "downloads.section": "Resources",
    "downloads.title": "Downloadable",
    "downloads.titleHighlight": "Documents",
    "downloads.subtitle": "Download the executive presentation in Spanish or English",
    "downloads.spanishTitle": "Executive Presentation",
    "downloads.spanishSubtitle": "Spanish Version",
    "downloads.spanishDesc": "Complete partnership proposal with market analysis, financial projections, deal structure and development roadmap.",
    "downloads.spanishPages": "PDF · 13 pages",
    "downloads.spanishBtn": "Download PDF",
    "downloads.englishTitle": "Executive Presentation",
    "downloads.englishSubtitle": "English Version",
    "downloads.englishDesc": "Complete partnership proposal with market analysis, financial projections, deal structure and development roadmap.",
    "downloads.englishPages": "PDF · 13 pages",
    "downloads.englishBtn": "Download PDF",
    "downloads.confidential": "Confidential documents. Please do not distribute without authorization.",

    // Contact Section
    "contact.cta": "Call to Action",
    "contact.title": '"The Ball Is in',
    "contact.titleHighlight": "Your Court",
    "contact.exclusiveUntil": "Exclusive Proposal Valid Until",
    "contact.deadline": "February 10, 2026",
    "contact.nextSteps": "Next Steps",
    "contact.step1": "Meeting",
    "contact.step2": "NDA",
    "contact.step3": "Due Diligence",
    "contact.step4": "Signing",
    "contact.ready": "Ready to take the next step?",
    "contact.contactNow": "Contact Now",

    // Footer
    "footer.rights": "© 2026 LINCE. All rights reserved.",
    "footer.ballInCourt": '"The ball is in your court"',
    "footer.confidential": "100% CONFIDENTIAL DOCUMENT",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
