/**
 * FictionalDisclaimer — Reusable component for legal disclaimers
 * about fictional characters inspired by real people.
 * 
 * Used in: Personajes.tsx,
 * ArtistChatModal.tsx, CharacterModal
 */

type Variant = "banner" | "badge" | "inline" | "chat";
type Lang = "es" | "en" | "zh" | "pt-BR" | "pt-PT";

interface FictionalDisclaimerProps {
  variant: Variant;
  lang?: Lang;
  realName?: string;
  className?: string;
}

const TEXTS: Record<string, Record<string, string>> = {
  es: {
    banner: "Todos los avatares de esta sección son personajes ficticios creados con IA con fines educativos. No representan ni están afiliados a ninguna persona real.",
    badge: "Personaje ficticio",
    badgeInspired: "Personaje ficticio",
    inline: "Este es un personaje ficticio creado con IA con fines educativos. No representa ni está afiliado a ninguna persona real.",
    chat: "Estás hablando con un personaje ficticio creado con IA. Las respuestas son generadas por inteligencia artificial y no representan las opiniones de ninguna persona real.",
  },
  en: {
    banner: "All avatars in this section are fictional AI-generated characters for educational purposes. They do not represent nor are affiliated with any real person.",
    badge: "Fictional character",
    badgeInspired: "Fictional character",
    inline: "This is a fictional AI-generated character for educational purposes. It does not represent nor is affiliated with any real person.",
    chat: "You are chatting with a fictional AI-generated character. Responses are generated by artificial intelligence and do not represent the opinions of any real person.",
  },
  zh: {
    banner: "本部分所有头像均为AI创建的虚构角色，仅用于教育目的。它们不代表也不隶属于任何真实人物。",
    badge: "虚构角色",
    badgeInspired: "虚构角色",
    inline: "这是一个为教育目的而创建的AI虚构角色。它不代表也不隶属于任何真实人物。",
    chat: "您正在与AI创建的虚构角色对话。回复由人工智能生成，不代表任何真实人物的观点。",
  },
};

export function FictionalDisclaimer({ variant, lang = "es", realName, className = "" }: FictionalDisclaimerProps) {
  const t = TEXTS[lang] || TEXTS.es;

  if (variant === "banner") {
    return (
      <div className={`flex items-start gap-2 px-4 py-3 bg-amber-500/5 border border-amber-500/15 rounded-lg ${className}`}>
        <span className="text-amber-400 text-sm flex-shrink-0 mt-0.5" aria-hidden="true">&#9888;</span>
        <p className="text-amber-400/70 text-xs leading-relaxed">{t.banner}</p>
      </div>
    );
  }

  if (variant === "badge") {
    return (
      <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[9px] font-medium bg-amber-500/10 text-amber-400/80 border border-amber-500/20 ${className}`}>
        <span aria-hidden="true">&#9888;</span>
        {realName ? `${t.badgeInspired} ${realName}` : t.badge}
      </span>
    );
  }

  if (variant === "chat") {
    return (
      <div className={`flex items-start gap-2 px-3 py-2 bg-amber-500/5 border border-amber-500/10 rounded-lg ${className}`}>
        <span className="text-amber-400/60 text-xs flex-shrink-0 mt-0.5" aria-hidden="true">&#9888;</span>
        <p className="text-amber-400/50 text-[10px] leading-relaxed">{t.chat}</p>
      </div>
    );
  }

  // inline
  return (
    <p className={`text-amber-400/50 text-[10px] leading-relaxed italic ${className}`}>
      <span aria-hidden="true">&#9888;</span> {t.inline}
    </p>
  );
}

export { TEXTS as DISCLAIMER_TEXTS };
